import org.gradle.api.tasks.bundling.AbstractArchiveTask
plugins {
    id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group
base.archivesName = project.archives_base_name

// jar name rule: [vpl-<version>-for-<mc support range>]carpet-addition-<version>.jar
tasks.withType(AbstractArchiveTask).configureEach {
    if (name != 'jar' && name != 'sourcesJar') return
    def suffix = (name == 'sourcesJar') ? '-sources' : ''
    archiveFileName = "[vpl-${project.version}-for-${project.mc_support_range}]carpet-addition-${project.version}${suffix}.${archiveExtension.get()}"
}

repositories {
    maven { url 'https://masa.dy.fi/maven' }
    maven { url 'https://maven.fabricmc.net/' }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    implementation "carpet:fabric-carpet:${project.carpet_version}"
    include(annotationProcessor("io.github.llamalad7:mixinextras-fabric:0.4.1"))
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

processResources {
    inputs.property "version", project.version
    inputs.property "mod_id", project.mod_id
    inputs.property "mod_name", project.mod_name
    filteringCharset = "UTF-8"
    filesMatching("fabric.mod.json") {
        expand project.properties
    }
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}
