org.gradle.jvmargs=-Xmx2G
minecraft_version=1.21.11
loader_version=0.17.3
fabric_version=0.140.0+1.21.11
carpet_version=1.21.11-1.4.194+v260107
carpet_dep_version=1.21.11-1.4.194+v260107
mod_id=carpet-vpl-addition
mod_name=Carpet VPL Addition
mod_version=1.14.2
maven_group=carpetvpladdition
archives_base_name=[vpl26.2]carpet-vpl-addition
