org.gradle.jvmargs=-Xmx2G
minecraft_version=26.2
loader_version=0.19.3
fabric_version=0.154.2+26.2
carpet_version=26.2+v260616
carpet_dep_version=26.2+v260616
mod_id=carpet-vpl-addition
mod_name=Carpet VPL Addition
mod_version=1.14.1
maven_group=carpetvpladdition
archives_base_name=[vpl26.2]carpet-vpl-addition
